"""empty message

Revision ID: 775c1e7dbf35
Revises: bd337e44ac43
Create Date: 2024-01-11 15:46:25.844318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775c1e7dbf35'
down_revision = 'bd337e44ac43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
